### ISSUE TITLE
[Question] Understanding the name

### ISSUE THREAD

**Issue by arjun27** [hdorgeval/playwright-fluent#1]
Hi! This looks like a great project. I'm curious to know why the package is called playwright-controller. I'm new to the Fluent pattern, and I'm probably missing something about the role of "controller"

**Comment by hdorgeval** [comment]
Hi @arjun27, thank you for your interest in this project. 
I admit that the name of this project is questionable. If you think it could have a better name, please, propose another name.

This name came from [TestCafe](https://github.com/DevExpress/testcafe) which exposes a fluent API. 

In TestCafe,  a typical test looks like: 

```js
await t
 .navigateTo(url)
 .hover(selector)
 .click(selector)
 ... etc ...

```

The `t` object that gives access to all chainable actions and assertions is called the `TestCafe controller`.

**Comment by arjun27** [comment]
Ah, thanks for the explanation. I was trying to figure out how "controller" fits in the fluent ecosystem and that explains it. However, it might be worth evaluating if "controller" is an implementation detail chosen by Testcafe. I was wondering if playwright-fluent might better convey the intent of the project.

**Comment by hdorgeval** [comment]
`playwright-fluent` looks like a great name 👍 🥇 . 

Thanks a lot for this suggestion.

Please make some noise on this thread to see if this name fits more than the actual one. 
I propose you to wait some days before changing the name of the project and of the npm package in favor of your suggestion.

**Comment by hdorgeval** [comment]
Hi @arjun27 , thank you for your feedback!
