### ISSUE TITLE
Api to handle dialogs and alerts.

### ISSUE THREAD

**Issue by osolomin90** [hdorgeval/playwright-fluent#15]
**Is your feature request related to a problem? Please describe.**
Yes to check dialog or alert I have to switch on pure Playwright. 
**Describe the solution you'd like**
a few more api functions to expect dialog or alert with expected text and a few functions to accept and dismiss them. 
**Describe alternatives you've considered**
Currently I have to call currentPage() and use page.on('dialog', ...) but with TS it make me handle optional chaining) due to return type of  currentPage().
**Additional context**
I am trying to wright tests without pure Playwright because it allows me to create very readable code plus Playwright-Fluent acts more like real user. I really like use this wrapper.

**Comment by hdorgeval** [comment]
Hi @osolomin90 , thank you for your feedback!

I will start to implement what you need :)

**Comment by hdorgeval** [comment]
Hi @osolomin90 , I have published on npm the v1.42.0 that provides the new API on Dialogs.

You can read the details of the release here : https://github.com/hdorgeval/playwright-fluent/releases/tag/v1.42.0

Do not hesitate to give any feedback if something does not fit your needs.
