### ISSUE TITLE
Can not start chrome in docker

### ISSUE THREAD

**Issue by osolomin90** [hdorgeval/playwright-fluent#19]
**Describe the bug**
withBrowser('chrome') do not work in docker. 
**To Reproduce**
**_Environment - Dockerfile:_**
FROM mcr.microsoft.com/playwright:focal

WORKDIR tests

COPY package.json /tests

RUN npm install
RUN npx playwright install chrome --with-deps

COPY cucumber.ts /tests
COPY tsconfig.json /tests
COPY src /tests/src

ENTRYPOINT ["npm", "run", "test:pipeline"]

**_Script:_**
playwright
        .withBrowser('chrome')
        .withOptions({headless: props.isHeadless, slowMo: 50})
        .withDefaultWaitOptions({stabilityInMilliseconds: 50, timeoutInMilliseconds: PLAYWRIGHT_TIMEOUT})
        .withDefaultAssertOptions({stabilityInMilliseconds: 100, timeoutInMilliseconds: 3000})
        .WithDialogs();

**_ERROR:_** browserType.launch: Failed to launch chromium because executable doesn't exist at google-chrome-stable

**_But it works with next script:_** 
 async function main() {
        const browser = await playwright['chromium'].launch({
            channel: 'chrome'
        });
        const page = await browser.newPage();
        await page.goto('https://google.com');
        await browser.close();
        console.log("DONE!")
 };
main();

**Expected behavior**
Both scripts should work with chrome 

**Additional context**
Both scripts works as expected on my mac book pro with Big Sur.
Also I found that I can not add 'channel' property to withOptions(...).

**Comment by hdorgeval** [comment]
Hi @osolomin90, thank you for your feedbacks. 
To be honest I need some time to investigate running playwright-fluent in docker and looking why the 'google-chrome-stable' is not working.

Meanwhile, I will fix the missing `channel: 'chrome'` in the withOptions so that you have a workaround.
Thanks!

**Comment by osolomin90** [comment]
Hi, @hdorgeval did a for of your repo, found that you have skipped test 'should target chrome' allowed this test and started checks in my fork. Test fails exactly with the same issue:
FAIL src/fluent-api/tests/with-browser/with-browser.test.ts
  ● Playwright Fluent - withBrowser › should target chrome

    browserType.launch: Failed to launch chromium because executable doesn't exist at google-chrome-stable

       99 |           executablePath: getChromePath(),
      100 |         };
    > 101 |         const browser = await chromium.launch(chromeOptions);
          |                                        ^
      102 |         return browser;
      103 |       }
      104 |     }

      at Object.launchBrowser (src/actions/browser-actions/launch-browser/launch-browser.ts:101:40)
      at PlaywrightFluent.launchBrowser (src/fluent-api/playwright-fluent.ts:431:33)
      at action (src/fluent-api/playwright-fluent.ts:524:46)
      at PlaywrightFluent.executeActions (src/fluent-api/playwright-fluent.ts:282:26)
      at PlaywrightFluent.then (src/fluent-api/playwright-fluent.ts:264:23)
      
So I am will try to help find and fix this issue.

**Comment by hdorgeval** [comment]
Hi @osolomin90, thank you so much for pointing this, I will check this on my side and try to run it on Github CI.
Thanks !

**Comment by osolomin90** [comment]
Hi @hdorgeval, I already investigated and fixed that one in my fork. Here is the branch with fix: https://github.com/osolomin90/playwright-fluent/tree/linux-chrome-bug 
If if is good for your opinion I can do PR.

**Comment by hdorgeval** [comment]
Hi @osolomin90, thanks a lot, I did look to what you have done in your fork.

I am currently reporting your code change of the `getChromePath()` function. I am still working on it because it needs some adaptation of existing tests and some changes in the appveyor ci configuration to make the unskipped test pass.

Nonetheless, it would be great to have you as official contributor on playwright-fluent, and a PR on setting up a docker env would be great!

**Comment by osolomin90** [comment]
@hdorgeval I really appreciate your proposal and will gladly accept it. Looking very much forward to our cooperation. Let me know what with witch part of issues I can help to avoid doing the same job.

**Comment by hdorgeval** [comment]
Hi @osolomin90 , the fix is now available on the published package v1.45.0.
Feel free to give any feedback if the fix does not work as expected.
