### ISSUE TITLE
Check node version

### ISSUE THREAD

**Issue by franckLdx** [hdorgeval/playwright-fluent#6]
**Is your feature request related to a problem? 
We've just lost time to understand why our tests could not execute on some agents. It appears that node on those agents was still old 12 version, while playwright-fluent needs node 14 or more.

**Describe the solution you'd like**
Add an engine constraints in package.json to get a relevant message when an old node version is used.
[engines check description](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines)

**Comment by hdorgeval** [comment]
Hi @franckLdx , previous test runs on Travis and Appveyor showed that playwright-fluent runs on node 12 with playwright v1.7, so I would be glad if you could describe more precisely which part of playwright-fluent needs node 14 or more. Thanks.

**Comment by hdorgeval** [comment]
Hi @franckLdx , my bad, you are perfectly right, let me fix this asap

**Comment by hdorgeval** [comment]
Hi @franckLdx , I just updated my previous comment and I need your point of view. Thanks

**Comment by hdorgeval** [comment]
Hi @franckLdx , I just published v1.16.1 that should work on node 12 and 14.
