### ISSUE TITLE
Select item by value

### ISSUE THREAD

**Issue by franckLdx** [hdorgeval/playwright-fluent#7]
**Is your feature request related to a problem? Please describe.**
I would like to select an item by value and not by label

**Describe the solution you'd like**
Having a `selectByValue` that works like `select`

**Comment by hdorgeval** [comment]
Hi @franckLdx, thank you for your feedback, I will implement this feature asap.

**Comment by hdorgeval** [comment]
Hi @franckLdx , I have published v1.17.0 with the feature you have asked for.
