### ISSUE TITLE
Iframe api.

### ISSUE THREAD

**Issue by osolomin90** [hdorgeval/playwright-fluent#9]
**Is your feature request related to a problem? Please describe.**
I use raw playwright to test service with several iframes, I would like to use Playwright-fluent but when I get frame content I can not continue use fluent api.  

**Describe the solution you'd like**
1. Methods to switch to frame and back.
2. PlaywrightFluent constructor can accept Page | Frame.

**Comment by hdorgeval** [comment]
Hi @osolomin90, thank you for your feedback. 

It could be great if you can share some 'raw'  playwright code with iframes that you have implemented, so that I can test it on my side when building a fluent API around iFrames.
Thanks!

**Comment by osolomin90** [comment]
Sure, here you are:

Page with I frame class:

export class FakeAppPage{

    private readonly page: Page;
    private readonly docFrameSelector = "iframe[src*='document-manager']";

    constructor(page: Page){
        this.page = page;
    }

    async getDocPage(): Promise<DocumentPage>{
        return allure.step("Get Doc page", async ()=>{
            let elementHandle = await this.page.waitForSelector(this.docFrameSelector, {state: 'visible'});
            const docFrame: any = await elementHandle.contentFrame();
            expect(docFrame).not.toBeNull();
            return new DocumentPage(docManagerFrame);
        })
    }

    async getDocFrame(): Promise<Frame>{
        return allure.step("Get Doc frame", async ()=>{
            let elementHandle = await this.page.waitForSelector(this.docFrameSelector, {state: 'visible'});
            const docFrame: any = await elementHandle.contentFrame();
            expect(docFrame).not.toBeNull();
            return docFrame;
        })
    }
}

============================================================================================
And abstract class for all pages inside (Iframe context), I use page object:

import {ElementHandle, Frame} from "playwright";

const AssertionError = require('assert').AssertionError;

export class AbstractWeb {

    protected readonly docFrame: Frame;

    /**
     * @param {Frame} docFrame - The Playwright Frame
     * @param {string} [selector] - How to select this modal. If missing this will be a catch-all modal selector so you
     * may actually get a different modal to that which you expected.
     */
    constructor(docFrame: Frame) {
        /** @type Frame */
        this.docFrame = docFrame;
    }

    /**
     * Checks if any selector is hidden
     * @param {string} selector
     * @returns {Promise<any>}
     */
    async verifyIfSelectorIsHidden(selector: string) {
        return await allure.step(`Verify if selector '${selector}' is hidden.`, async () => {
            try {
                return this.docFrame.waitForSelector(selector, {state: "hidden", timeout: 5000});
            } catch (error) {
                throw new AssertionError({
                    message: error.message,
                    actual: `'${selector}' is not hidden`,
                    expected: `'${selector}' is hidden`,
                    stackStartFn: error.stackStartFn
                });
            }
        })
    }

    /**
     * Checks if any selector is visible
     * @param  {string} selector
     * @returns {Promise<any>}
     */
    async verifyIfSelectorIsVisible(selector: string): Promise<ElementHandle> {
        return await allure.step(`Verify if selector '${selector}' shown`, async () => {
            try {
                // in case 'waitForSelector' will not find visible element it will throw Timeout Error.
                // 'expect(element.isVisible()).toBeTruly()' will work only in happy path,
                // and will not be executed if element will not be visible
                return this.docFrame.waitForSelector(selector, {state: "visible"});
            } catch (error) {
                throw new AssertionError({
                    message: error.message,
                    actual: `'${selector}' is not visible`,
                    expected: `'${selector}' is visible`,
                    stackStartFn: error.stackStartFn
                });
            }
        })
    }

    async waitTillSelectorIsVisibleAndStable(selector: string) {
        await allure.step(`Verify if selector '${selector}' is visible and stable.`, async () => {
            const element = await this.verifyIfSelectorIsVisible(selector);
            await element.waitForElementState("stable");
        })
    }

**Comment by hdorgeval** [comment]
Hi @osolomin90, thank you for sharing your code.

I just started to implement a fluent version of the playwright iframe API.

**Comment by hdorgeval** [comment]
Hi @osolomin90 , I just release [v1.29.0](https://github.com/hdorgeval/playwright-fluent/releases/tag/v1.29.0) that implements a fluent version of the playwright iframe API.

This new version has:
1. Methods to switch to frame and back.
2. PlaywrightFluent constructor can now accept Page | Frame.

Do not hesitate to give any feedback.
Thanks
